{"version":1,"defects":{"Warning":6,"Tests\\Unit\\RouterTest::it_registers_a_post_route":3,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #2":3,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #3":3,"Error":4,"Tests\\Unit\\RouterTest::it_resolves_a_route_from_a_class_method":4,"Tests\\Unit\\Services\\InvoiceServiceTest::it_process_the_invoice_correctly":3,"Tests\\Unit\\Services\\InvoiceServiceTest::it_sends_receipt_email_when_processing_the_invoice":3},"times":{"Warning":0,"Tests\\Unit\\RouterTest::it_registers_a_route":0.008,"Tests\\Unit\\RouterTest::it_registers_a_get_route":0,"Tests\\Unit\\RouterTest::it_registers_a_post_route":0,"Tests\\Unit\\RouterTest::there_are_no_routes_when_router_is_created":0,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #0":0.002,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #1":0,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #2":0,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #3":0,"Error":0.001,"Tests\\Unit\\RouterTest::it_resolves_a_route_from_a_closure":0,"Tests\\Unit\\RouterTest::it_resolves_a_route_from_a_class_method":0.001,"Tests\\Unit\\Services\\InvoiceServiceTest::it_process_the_invoice_correctly":0.014,"Tests\\Unit\\Services\\InvoiceServiceTest::it_sends_receipt_email_when_processing_the_invoice":0,"Tests\\Unit\\Services\\InvoiceServiceTest::it_sends_receipt_email_when_the_invoice_is_processed":0.001}}